baseURL: https://www.desmondbourgeois.com/
languageCode: en-us
title: DB PhD
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to my Website!"
    Content: Hello, I am an Assistant Professor. I like to wirte and my job is to publish. The content that does not make it to the research papers or grants finds a home here. My views are my own.
  socialIcons:
    - name: twitter
      url: "https://twitter.com/_dbourgeois"
    - name: github
      url: "https://github.com/djbourg"

  DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
